wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693182735.369185
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 2
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.32.0
      8:
      - 1
      - 5
    session_history: code/_session_history.ipynb
