version: '3'
services:
  llm-finetuning-cicd:
    build: .
    image: olachinkei/llm-finetuning-cicd
    container_name: llm-finetuning-cicd
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}ß
      - WANDB_API_KEY=${WANDB_API_KEY}
    working_dir: /work
    volumes:
      - ./src:/work
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost

    


