wandb_version: 1

BASE_MODEL:
  desc: null
  value: facebook/opt-125m
MODEL_REGISTRY:
  desc: null
  value: Instruction-tuned-model
_wandb:
  desc: null
  value:
    code_path: code/evaluation.py
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.32.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693352113.767522
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      6: 4.32.0
      8:
      - 5
